name: Build
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build firmware
        uses: unifiedware/zmk-build-action@main
        with:
          board: keychron_b1_pro_ansi
